const naturalSubcategories = [
  "Mountains",
  "Hill Stations",
  "Beaches",
  "Waterfalls",
  "Lakes",
  "Forests",
  "Deserts",
  "Caves",
  "Valleys",
  "Islands",
];
const culturalSubcategories = [
  "Historical Monuments",
  "Forts & Palaces",
  "Temples",
  "Mosques",
  "Churches & Cathedrals",
  "Gurudwaras",
  "Cultural Villages",
  "Archaeological Sites",
  "Museums & Galleries",
  "Stepwells (Baolis)",
  "Heritage Cities",
  "Colonial Architecture",
  "Cultural Festivals",
  "Ruins & Ancient Cities",
  "UNESCO Heritage Sites"
];
const urbanSubcategories = [
  "Skyscrapers & Cityscapes",
  "Shopping Malls & Markets",
  "Nightlife & Clubs",
  "Cafés & Restaurants",
  "Business Hubs",
  "Urban Parks & Gardens",
  "Art Galleries & Exhibitions",
  "Concerts & Events",
  "Amusement & Theme Parks",
  "City Landmarks",
  "Urban Lakes & Waterfronts",
  "Public Transit & Metro Rides",
  "Modern Architecture",
  "Smart Cities",
  "Luxury Hotels & Skyscraper Stays"
];
const themeParkSubcategories = [
  "Amusement Parks",
  "Water Parks",
  "Adventure Parks",
  "Wildlife & Safari Parks",
  "Snow & Ice Parks",
  "Fantasy & Movie Theme Parks",
  "Kid-Friendly Theme Parks",
  "Virtual Reality (VR) Parks",
  "Cultural Theme Parks",
  "Tech & Science Parks",
  "Indoor Theme Parks",
  "Educational Parks",
  "Festival & Seasonal Parks",
  "Eco & Nature Theme Parks",
  "Resort-Based Theme Parks"
];
const wellnessSpiritualSubcategories = [
  "Spiritual Retreats",
  "Yoga Retreats",
  "Ayurveda & Spa Resorts",
  "Pilgrimage Sites",
  "Temples & Shrines",
  "Churches, Mosques, Gurudwaras",
  "Ashrams",
  "Meditation Centres",
  "Sacred Rivers & Ghats",
  "Caves & Monastic Sites",
  "Healing Forest Retreats",
  "Spiritual Festivals",
  "Energy Centers (Power Spots)",
  "Silent Retreats",
  "Eco-Spiritual Villages"
];
const adventureSportsSubcategories = [
  "Trekking & Hiking",
  "Camping",
  "River Rafting",
  "Bungee Jumping",
  "Rock Climbing",
  "Paragliding",
  "Skydiving",
  "Ziplining / Flying Fox",
  "ATV & Off-Roading",
  "Skiing & Snowboarding",
  "Scuba Diving & Snorkeling",
  "Surfing & Jet Skiing",
  "Hot Air Balloon Rides",
  "Wildlife Safaris",
  "Horse & Camel Riding",
  "Cycling & Mountain Biking",
  "Caving & Spelunking",
  "Zip Biking & Rope Cycling",
  "Waterfall Rappelling",
  "Kite Surfing"
];
const culinarySubcategories = [
  "Street Food Tours",                   
  "Regional Cuisine Exploration",        
  "Wine & Brewery Tours",                
  "Cooking Classes & Workshops",         
  "Food Festivals & Culinary Events",    
  "Farm-to-Table Experiences",           
  "Seafood & Coastal Cuisine Trails",    
  "Tea/Coffee Plantation Tours",        
  "Dessert & Sweet Trails"               
];
const offbeatAndRemoteSubcategories = [
  "Hidden Villages & Hamlets",               
  "Tribal Region Explorations",              
  "Monastic Retreats & Meditation Centers",  
  "Remote Mountain Escapes",                 
  "Forest & Jungle Retreats",                
  "Deserted Islands & Beach Getaways",      
  "Snow Villages & Frozen Towns",           
  "Nomadic Life Experiences",                
  "Cultural Immersion Homestays",            
  "Volunteering & Rural Development Trips"   
];
